package com.pga;
// Generated Oct 6, 2018 10:25:25 AM by Hibernate Tools 5.3.1.Final

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int eno;
	private Dept dept;
	private String ename;
	private Float esalary;

	public Employee() {
	}

	public Employee(int eno) {
		this.eno = eno;
	}

	public Employee(int eno, Dept dept, String ename, Float esalary) {
		this.eno = eno;
		this.dept = dept;
		this.ename = ename;
		this.esalary = esalary;
	}

	public int getEno() {
		return this.eno;
	}

	public void setEno(int eno) {
		this.eno = eno;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Float getEsalary() {
		return this.esalary;
	}

	public void setEsalary(Float esalary) {
		this.esalary = esalary;
	}

	@Override
	public String toString() {
		return "[eno=" + eno + ", dept=" + dept + ", ename=" + ename + ", esalary=" + esalary + "]";
	}

}
