package com.pga;
// Generated Oct 6, 2018 9:19:37 AM by Hibernate Tools 5.3.1.Final

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private int eid;
	private String name;
	private Float salary;

	public Emp() {
	}

	public Emp(int eid) {
		this.eid = eid;
	}

	public Emp(int eid, String name, Float salary) {
		this.eid = eid;
		this.name = name;
		this.salary = salary;
	}

	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getSalary() {
		return this.salary;
	}

	public void setSalary(Float salary) {
		this.salary = salary;
	}

}
