package com.pga;
// Generated Oct 6, 2018 10:25:25 AM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private int dno;
	private String dname;
	private Set employees = new HashSet(0);

	public Dept() {
	}

	public Dept(int dno) {
		this.dno = dno;
	}

	public Dept(int dno, String dname, Set employees) {
		this.dno = dno;
		this.dname = dname;
		this.employees = employees;
	}

	public int getDno() {
		return this.dno;
	}

	public void setDno(int dno) {
		this.dno = dno;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
